# Generated by Django 5.2.17 on 2026-09-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
    ]
