# Generated by Django 5.2.17 on 2026-09-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_leave_leavebalance'),
        ('hr', '0003_alter_department_id_alter_designation_id_and_more'),
    ]

    operations = [
    ]
