# Generated by Django 5.2.17 on 2026-09-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_payroll'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='hr_department',
        ),
    ]
